### ISSUE TITLE
api key

### ISSUE THREAD

**Issue by kennyfs** [wonderingabout/gtp2ogs-tutorial#1]
How to get API key?
I don't understand.
I can't find the button.

**Comment by wonderingabout** [comment]
hi @kennychenfs 

this is what you need to have an apikey

- 1) your bot account needs to have a grey name
- 2) log in from your ogs USER account (for example for me metaphysician splurgist :) ), and visit the profile page of your ogs BOT account, for example for me meta-金毛测试-20b : 

the apikey will appear here : 

![img](https://github.com/wonderingabout/gtp2ogs-tutorial/raw/master/pictures/beta%202.png?raw=true)

i just updated the apikey page, i hope its a bit clearer now : 
https://github.com/wonderingabout/gtp2ogs-tutorial/blob/master/docs/2-common-generate-the-apikey.md

**Comment by kennyfs** [comment]
Thank you, I found it on my administrator account yesterday.

wonderingabout <notifications@github.com> 於 2019年1月23日 週三 下午6:03寫道：

**Comment by wonderingabout** [comment]
welcome :+1: 

i hope that you will have fun running your bot on ogs :)

what is the bot you'll run on ogs ? :)

**Comment by kennyfs** [comment]
lz192X15, this weight is trained by bjiyxo.
When I make games between it and elf.
I found if I give them same time limit, They are about the same strength.
So I started to test it.

wonderingabout <notifications@github.com> 於 2019年1月23日 週三 下午6:25寫道：

**Comment by wonderingabout** [comment]
have fun @kennychenfs :)

roy7 bots use time management so they will play with less visits if time is short
however elf was increased very recently from 1600 to 3200 visits, which should have been done a lot sooner considering it is 20b (faster to compute moves)

my bot doesnt use time mangement though
anyways have fun, and dont hesitate to come on the discord to chat with other bot admins and all people :) 

https://discord.gg/HZ23Cp9

**Comment by wonderingabout** [comment]
@kennychenfs 

also someone else is running 15bTurboLeela too : 
https://online-go.com/player/602660/15bTurboLeela

have fun :)

**Comment by wonderingabout** [comment]
@kennychenfs 

also, you are welcome on the OGS AI tournaments group if you want to participate 

https://online-go.com/group/3211
